SCALED_IMAGE_HEIGHT = 300
SCALED_IMAGE_WIDTH = 480

ORIGINAL_IMAGE_HEIGHT = 1024
ORIGINAL_IMAGE_WIDTH = 1920

HEIGHT_SCALED_RATIO = ORIGINAL_IMAGE_HEIGHT / SCALED_IMAGE_HEIGHT
WIDTH_SCALED_RATIO = ORIGINAL_IMAGE_WIDTH / SCALED_IMAGE_WIDTH
